export const Users = [
    {
        id: 1,
        profilePicture: "https://www.nicepng.com/png/full/166-1667644_dbz-dragon-ball-z-transparent-dragonball-z-gohan.png",
        username: "Gohan",
    },
    {
        id: 2,
        profilePicture: "https://geekvibesnation.com/wp-content/uploads/2018/09/55A1A523-D6E3-4680-908F-FA6D78E054CE.jpeg",
        username: "Goten",
    },
    {
        id: 3,
        profilePicture: "https://64.media.tumblr.com/f22c8392c0f6018cef9cf5e195fd180b/127056b7f8653306-64/s640x960/8cb3f6f0fe2e141f76bfc473007b42557f757f6b.jpg",
        username: "Trunks",
    },
    {
        id: 4,
        profilePicture: "http://images5.fanpop.com/image/photos/25400000/Android-18-dragonball-z-android-18-vs-bulma-25478070-1920-1200.jpg",
        username: "Lazuli",
    },
    {
        id: 5,
        profilePicture: "https://static0.srcdn.com/wordpress/wp-content/uploads/2020/10/Dragon-Ball-Super-Shenron-Android-17.jpg",
        username: "Lapis",
    },
    {
        id: 6,
        profilePicture: "https://i0.wp.com/alfabetajuega.com/hero/2022/05/goku-dragon-ball.1651847419.5233.jpg",
        username: "Goku",
    },
    {
        id: 7,
        profilePicture: "https://i2.wp.com/alfabetajuega.com/hero/2022/04/Se-ha-confirmado-oficialmente-cual-es-la-forma-mas-poderosa-de-Vegeta.jpg",
        username: "Vegeta",
    },
    {
        id: 8,
        profilePicture: "https://numpaint.com/wp-content/uploads/2021/01/Picollo-dragon-balll-paint-by-numbers.jpg",
        username: "Piccolo",
    },
    {
        id: 9,
        profilePicture: "https://oyster.ignimgs.com/mediawiki/apis.ign.com/dragon-ball-fighterz/0/0b/Super_Krillin.jpg",
        username: "Krillin",
    },
    {
        id: 10,
        profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL_VwOEeceT4t2aFjIxUIY5jezk_zr_FHXmKm0Z3MRAx6Wc-_pey-DnMTHQUNMUeU17GQ&usqp=CAU",
        username: "Bulma",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        photo: "https://wallpaperaccess.com/full/4545965.png",
        date: "2 mins ago",
        userId: 1,
        like: 19,
        comment: 9,
    },
    {
        id: 2,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        photo: "https://hdwallpaperim.com/wp-content/uploads/2017/08/22/104513-Dragon_Ball_Z.jpg",
        date: "2 mins ago",
        userId: 2,
        like: 19,
        comment: 9,
    },
    {
        id: 3,
        photo: "https://wallpaperaccess.com/full/340768.jpg",
        date: "2 mins ago",
        userId: 3,
        like: 19,
        comment: 9,
    },
    {
        id: 4,
        desc: "Lorem ed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        photo: "https://cdn.wallpapersafari.com/34/80/BTkNmJ.jpg",
        date: "2 mins ago",
        userId: 4,
        like: 19,
        comment: 9,
    },
    {
        id: 5,
        desc: "Lorem ipsum dolor ncididunt ut labore et dolore magna aliqua.",
        photo: "https://www.denofgeek.com/wp-content/uploads/2018/11/dragon_ball_super_86-2.jpg?fit=1280%2C720",
        date: "2 mins ago",
        userId: 5,
        like: 19,
        comment: 9,
    },
    {
        id: 6,
        photo: "https://www.teahub.io/photos/full/4-43882_dragon-ball-background-hd.jpg",
        date: "2 mins ago",
        userId: 6,
        like: 19,
        comment: 9,
    },
    {
        id: 7,
        desc: "Lorem ipsum dolor sit amet, consectet",
        photo: "http://images5.fanpop.com/image/photos/25500000/dbz-villains-dragon-ball-z-25544599-1131-707.jpg",
        date: "2 mins ago",
        userId: 7,
        like: 19,
        comment: 9,
    },
    {
        id: 8,
        photo: "https://c4.wallpaperflare.com/wallpaper/198/274/338/dragon-ball-z-wallpaper-thumb.jpg",
        date: "2 mins ago",
        userId: 8,
        like: 19,
        comment: 9,
    },
    {
        id: 9,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        photo: "https://feedride.com/wp-content/uploads/2020/04/Dragon_Ball-Dragon_Ball_Z.jpg",
        date: "2 mins ago",
        userId: 9,
        like: 19,
        comment: 9,
    },
    {
        id: 10,
        photo: "https://i.pinimg.com/originals/76/8d/85/768d8569299c97d24532ac413c6c57ac.png",
        date: "2 mins ago",
        userId: 10,
        like: 19,
        comment: 9,
    },
];